# Generated by Django 6.0.2 on 2026-03-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='model_name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_data',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='source',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
