# Generated by Django 6.0.2 on 2026-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('instance_id', models.PositiveIntegerField()),
                ('rule_name', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('repeat_every', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='model_trigg_status_b05389_idx')],
                'constraints': [models.UniqueConstraint(fields=('model', 'instance_id', 'rule_name'), name='unique_scheduled_rule_per_instance')],
            },
        ),
    ]
